model_id: yolo26n
display_name: "YOLO26n"
batch_processing_mode: "default"

params:
  model_path: "path/to/yolo26n.pt"
  device: "cpu"
  conf_threshold: 0.25
  iou_threshold: 0.45

widgets:
  - name: button_run
    value: null
  - name: button_classes_filter
    value: null
  - name: input_conf
    value: null
  - name: edit_conf
    value: 0.25
  - name: input_iou
    value: null
  - name: edit_iou
    value: 0.70
  - name: toggle_preserve_existing_annotations
    value: false